(require 'package)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
(package-initialize)
(setq inhibit-startup-screen t)
(require 'evil)
(require 'linum-relative)
(require 'powerline)
(powerline-evil-center-color-theme)
(display-time-mode t)
(linum-relative-global-mode)
(setq linum-relative-current-symbol "")
(evil-mode 1)
(add-to-list 'custom-theme-load-path "~/.emacs.d/themes/")
(load-theme 'monokai t)
(menu-bar-mode -1) 
(tool-bar-mode -1) 
(toggle-scroll-bar -1) 
(define-key evil-normal-state-map (kbd "j") 'evil-next-visual-line)
(define-key evil-normal-state-map (kbd "k") 'evil-previous-visual-line)
